name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code 
      uses: actions/checkout@v4

    - name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'

    - name: Build And Run Tests
      run: gradle clean build --info --stacktrace
      
    - name: Upload JAR to file store
      uses: JantHsueh/upload-file-action@master
      with:
        url: https://file.io
        forms: '{"Authorization":"Bearer ${{ secrets.FILE_IO_API_KEY }}"}'
        fileForms: '{"file":"build/libs/task-1.0.0.jar"}'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ximtech/btcbit-homework